### PR TITLE
Pipe FFmpeg output to a function

### PR DESCRIPTION
**Pull request by videowala**
Sometimes it is required to save the output directly to cloud storage or stream the output as the response.
I have added a config function `pipeOutputTo` which will be called from `convertProcess.stdout.pipe(config.pipeOutputTo);`

If the option is passed the output option will be ignored and the file will not be saved to the disk.
[Here is an example](https://gist.github.com/videowala/be31ace4ec2f9ff21f09478a6ccc15c6) of storing the output directly to the S3 bucket.

### CODE REVIEW

**Comment by vincaslt** [comment]
Any idea if this could be merged at some point?

**Comment by tungs** [comment]
I like the idea behind the feature, but I have some minor implementation and style concerns. I'll try to review the code and make some suggestions this week. How necessary is it to use `-movflags frag_keyframe+empty_moov+faststart` when piping? I'd rather they be optional, configurable arguments.

**Comment by vincaslt** [comment]
There's a relevant discussion in https://github.com/fluent-ffmpeg/node-fluent-ffmpeg/issues/346 regarding `-movflags frag_keyframe+empty_moov+faststart`

**Comment by videowala** [comment]
It's been a while since I implemented this, but I guess those flags are required to stream the output. 
Please note that video these videos will not work on Twitter.

**Comment by tungs** [comment]
Much apologies for the very late response on this-- it dropped off my radar. Since it is so late, I made the changes I was going to recommend. In summary, I renamed `config.pipeOutputTo` to `config.outputStream`, and added `config.outputStreamOptions`, which allows specifying the output stream format and MOV muxer options, though by default it uses `'mp4'` and `'frag_keyframe+empty_moov+faststart'`. I also removed some of the `console.log`s since it can cause some problems in some scenarios.

The changes will be in the soon-to-be released version 0.2.0.

**Pull request merged**
